name: Assign PR Author

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign-pr-author:
    runs-on: ubuntu-latest

    steps:
      - name: Get pull request author
        id: pr_author
        run: echo "::set-output name=author::${{ github.event.pull_request.user.login }}"

      - name: Assign the PR author
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prAuthor = '${{ steps.pr_author.outputs.author }}';
            const prNumber = context.payload.pull_request.number;
            await github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              assignees: [prAuthor]
            });
