name: Discord Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - run: >
          curl -X
          POST -H 'Content-type:application/json'
          -d '{"content":"Hello, World!"}'
          ${{ secrets.DISCORD_WEBHOOK_URL }}
