name: Sync to Personal Repo

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ktb6/ktb6-teamblog
          ref: develop

      - name: Configure Git
        run: |
          git config --global user.name 'Danny-Jo'
          git config --global user.email 'dannyjo.world@gmail.com'

      - name: Add remote repository
        run: |
          git remote add personal https://github.com/Danny-Jo/ktb6-teamblog-mirror.git
          git fetch personal
          git rebase personal/main

      - name: Push changes
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git push personal develop --force
