name: Sync to Personal Repo

on:
  push:
    branches:
      - feature/KTB-34-test-PTA-secret-key-in-action

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: ktb6/ktb6-teamblog
          ref: develop

      - name: Configure Git
        run: |
          git config --global user.name 'Danny-Jo'
          git config --global user.email 'dannyjo.world@gmail.com'

      - name: Set up personal remote
        run: |
          git remote add personal https://Danny-Jo:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Danny-Jo/ktb6-teamblog-mirror.git

      # - name: Force push to personal repository
      #   run: |
      #     git push personal develop --force
      #   env:
      #     PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
