name: Trigger Sync on Personal Repo

on:
  push:
    branches:
      - feature/KTB-34-test-PTA-secret-key-in-action

jobs:
  trigger-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger sync workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/Danny-Jo/ktb6-teamblog-mirror/actions/workflows/sync-develop.yml/dispatches \
          -d '{"ref":"develop"}'
